//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.App.PresentationLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProcessing.App.PresentationLayer.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while applying a filter by the color channel..
        /// </summary>
        public static string ApplyColorFilter {
            get {
                return ResourceManager.GetString("ApplyColorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while applying the color matrix..
        /// </summary>
        public static string ApplyColorMatrix {
            get {
                return ResourceManager.GetString("ApplyColorMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while applying a convolution filter..
        /// </summary>
        public static string ApplyConvolutionFilter {
            get {
                return ResourceManager.GetString("ApplyConvolutionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while applying an RGB filter..
        /// </summary>
        public static string ApplyRgbFilter {
            get {
                return ResourceManager.GetString("ApplyRgbFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while buiding the plot..
        /// </summary>
        public static string BuildFunction {
            get {
                return ResourceManager.GetString("BuildFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been canceled..
        /// </summary>
        public static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while choosing a custom color matrix..
        /// </summary>
        public static string CustomColorMatrix {
            get {
                return ResourceManager.GetString("CustomColorMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening the file..
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the sequence of the operation..
        /// </summary>
        public static string Pipeline {
            get {
                return ResourceManager.GetString("Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while building quality measure histogram..
        /// </summary>
        public static string QualityHistogram {
            get {
                return ResourceManager.GetString("QualityHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting the information about random variable..
        /// </summary>
        public static string RandomVariableInfo {
            get {
                return ResourceManager.GetString("RandomVariableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while replacing the image..
        /// </summary>
        public static string ReplaceImage {
            get {
                return ResourceManager.GetString("ReplaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the file..
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening a color matrix menu..
        /// </summary>
        public static string ShowColorMatrixMenu {
            get {
                return ResourceManager.GetString("ShowColorMatrixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening a convolution filters menu..
        /// </summary>
        public static string ShowConvolutionMenu {
            get {
                return ResourceManager.GetString("ShowConvolutionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening a distributions filters menu..
        /// </summary>
        public static string ShowDistributionMenu {
            get {
                return ResourceManager.GetString("ShowDistributionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening an rgb filters menu..
        /// </summary>
        public static string ShowRgbMenu {
            get {
                return ResourceManager.GetString("ShowRgbMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening a settings menu..
        /// </summary>
        public static string ShowSettingsMenu {
            get {
                return ResourceManager.GetString("ShowSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while shuffling the image..
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while applying a histogram transformation..
        /// </summary>
        public static string TransformHistogram {
            get {
                return ResourceManager.GetString("TransformHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while undo/redo the last operation..
        /// </summary>
        public static string UndoRedo {
            get {
                return ResourceManager.GetString("UndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while zooming the image..
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
