<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <Authors>Daniil Dudin</Authors>
    <Company>Image Processing</Company>
    <Product>Microkernel</Product>
    <Description>Provides base components for the model-view-presenter pattern</Description>
    <PackageTags>mvp event-aggregator application-controller di-container</PackageTags>
    <RepositoryType></RepositoryType>
    <PackageProjectUrl>https://github.com/dudinda/Image-Processing</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dudinda/Image-Processing</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Copyright>Copyright (c) 2018-2026 Daniil Dudin</Copyright>
    <Version>2.0.0</Version>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes>
      -merged microkernel modules into one
      -renamed IContainer to IContainerAdapter
      -added support for dependency injection factories
      -added BeginScope support to IComponentProvider
      -added the ILoggerFactory in the app controller to generate loggers for presenters,
         and provide a custom implementation at the application level
      -made the application lifecycle non-static
      -added a monitor scope to adapt aggregator for integration tests
      -made the aggregator setter inside the controller public to allow integration tests to set it up
    </PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="LightInject" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Ninject.Extensions.NamedScope" Version="3.3.0" />
  </ItemGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName).UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\..\LICENSE.TXT" Link="LICENSE.TXT">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icon.png" Link="icon.png">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
</Project>
