<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ImageProcessing.App.Integration</RootNamespace>
    <AssemblyName>ImageProcessing.App.Integration</AssemblyName>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Code\Resources\Static\1920x1080frame.jpg" />
    <Content Include="Code\Resources\Static\2560x1440frame.jpg" />
    <Content Include="Code\Resources\Static\demo.gif" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Code\Resources\Res.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Res.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\ImageProcessing.App.UI\ImageProcessing.App.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.1.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="NUnit" Version="5.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>
</Project>