using System.Drawing;

using ImageProcessing.App.DomainLayer.Factories.ColorMatrix.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Convolution.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Distribution.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Recommendation.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Rotation.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Scaling.Implementation;
using ImageProcessing.App.DomainLayer.Factories.Transformation.Implementation;
using ImageProcessing.App.ServiceLayer.Models.AppSettings;
using ImageProcessing.App.ServiceLayer.Providers.BitmapLuminance;
using ImageProcessing.App.ServiceLayer.Providers.BitmapLuminance.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Convolution;
using ImageProcessing.App.ServiceLayer.Providers.Convolution.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Morphology;
using ImageProcessing.App.ServiceLayer.Providers.Morphology.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Rgb;
using ImageProcessing.App.ServiceLayer.Providers.Rgb.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Rotation;
using ImageProcessing.App.ServiceLayer.Providers.Rotation.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Scaling;
using ImageProcessing.App.ServiceLayer.Providers.Scaling.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Transformation;
using ImageProcessing.App.ServiceLayer.Providers.Transformation.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.VisitableFactory.BitmapLuminance;
using ImageProcessing.App.ServiceLayer.Providers.VisitableFactory.BitmapLuminance.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.VisitableFactory.Convolution;
using ImageProcessing.App.ServiceLayer.Providers.VisitableFactory.Convolution.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Visitors.BitmapLuminance;
using ImageProcessing.App.ServiceLayer.Providers.Visitors.BitmapLuminance.Implementation;
using ImageProcessing.App.ServiceLayer.Providers.Visitors.Convolution;
using ImageProcessing.App.ServiceLayer.Providers.Visitors.Convolution.Implementation;
using ImageProcessing.App.ServiceLayer.Services.BitmapCopyReference.Implementation;
using ImageProcessing.App.ServiceLayer.Services.BitmapCopyReference.Interface;
using ImageProcessing.App.ServiceLayer.Services.Bmp;
using ImageProcessing.App.ServiceLayer.Services.Bmp.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Cache;
using ImageProcessing.App.ServiceLayer.Services.Cache.Implementation;
using ImageProcessing.App.ServiceLayer.Services.ColorMatrix;
using ImageProcessing.App.ServiceLayer.Services.ColorMatrix.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Convolution;
using ImageProcessing.App.ServiceLayer.Services.Convolution.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Distribution;
using ImageProcessing.App.ServiceLayer.Services.Distribution.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Factories.ColorMatrix;
using ImageProcessing.App.ServiceLayer.Services.Factories.Convolution;
using ImageProcessing.App.ServiceLayer.Services.Factories.Distribution;
using ImageProcessing.App.ServiceLayer.Services.Factories.Morphology;
using ImageProcessing.App.ServiceLayer.Services.Factories.Morphology.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Factories.Recommendation;
using ImageProcessing.App.ServiceLayer.Services.Factories.Rgb;
using ImageProcessing.App.ServiceLayer.Services.Factories.Rgb.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Factories.Rotation;
using ImageProcessing.App.ServiceLayer.Services.Factories.Scaling;
using ImageProcessing.App.ServiceLayer.Services.Factories.Transformation;
using ImageProcessing.App.ServiceLayer.Services.FileDialog;
using ImageProcessing.App.ServiceLayer.Services.Locker;
using ImageProcessing.App.ServiceLayer.Services.LockerService.Operation.Implementation;
using ImageProcessing.App.ServiceLayer.Services.Morphology;
using ImageProcessing.App.ServiceLayer.Services.Morphology.Implementation;
using ImageProcessing.App.ServiceLayer.Services.NonBlockDialog;
using ImageProcessing.App.ServiceLayer.Services.Pipeline;
using ImageProcessing.App.ServiceLayer.Services.Pipeline.Implementation;
using ImageProcessing.App.ServiceLayer.Services.StaTask;
using ImageProcessing.App.ServiceLayer.Services.UndoRedo;
using ImageProcessing.App.ServiceLayer.Services.UndoRedo.Implementation;
using ImageProcessing.App.ServiceLayer.Win.Builders.ChartBuilder.Implementation;
using ImageProcessing.App.ServiceLayer.Win.Builders.ChartBuilder.Interface;
using ImageProcessing.App.ServiceLayer.Win.NonBlockDialog.Implementation;
using ImageProcessing.App.ServiceLayer.Win.ServiceModel.VisitableFactory.Histogram.Implementation;
using ImageProcessing.App.ServiceLayer.Win.ServiceModel.VisitableFactory.Histogram.Interface;
using ImageProcessing.App.ServiceLayer.Win.ServiceModel.Visitors.Histogram.Implementation;
using ImageProcessing.App.ServiceLayer.Win.ServiceModel.Visitors.Histogram.Interface;
using ImageProcessing.App.ServiceLayer.Win.Services.Histogram.Implementation;
using ImageProcessing.App.ServiceLayer.Win.Services.Histogram.Interface;
using ImageProcessing.App.ServiceLayer.Win.Services.Logger.Implementation;
using ImageProcessing.App.ServiceLayer.Win.Services.Logger.Interface;
using ImageProcessing.App.ServiceLayer.Win.Services.QualityMeasure.Implementation;
using ImageProcessing.App.ServiceLayer.Win.Services.QualityMeasure.Interface;
using ImageProcessing.Microkernel.AppConfig;
using ImageProcessing.Microkernel.MVP.IoC.Interface;

namespace ImageProcessing.App.PresentationLayer
{
    public sealed class Startup : IStartup
    {
        public void Build(IComponentProvider builder)
        {
            builder
                .RegisterSingleton<AppSettings>()
                .RegisterSingleton<ILoggerService, LoggerService>()
                .RegisterSingleton<IAwaitablePipeline, AwaitablePipeline>()
                .RegisterSingleton<IStaTaskService, StaTaskService>()
                .RegisterSingleton<IBitmapCopyService, BitmapCopyService>()
                .RegisterSingleton<ICacheService<Bitmap>, CacheService<Bitmap>>()
                .RegisterTransient<IUndoRedoService<Bitmap>, UndoRedoService>()
                .RegisterTransient<IConvolutionFactory, ConvolutionFactory>()
                .RegisterTransient<IMorphologyFactory, MorphologyFactory>()
                .RegisterTransient<IStructuringElementFactory, StructuringElementFactory>()
                .RegisterTransient<IDistributionFactory, DistributionFactory>()
                .RegisterTransient<IRgbFilterFactory, RgbFilterFactory>()
                .RegisterTransient<IScalingFactory, ScalingFactory>()
                .RegisterTransient<IColorMatrixFactory, ColorMatrixFactory>()
                .RegisterTransient<IRecommendationFactory, RecommendationFactory>()
                .RegisterTransient<IChannelFactory, ChannelFactory>()
                .RegisterTransient<IRotationFactory, RotationFactory>()
                .RegisterTransient<ITransformationFactory, TransformationFactory>()
                .RegisterTransient<IConvolutionService, ConvolutionService>()
                .RegisterTransient<IMorphologyService, MorphologyService>()
                .RegisterTransient<IBitmapService, BitmapService>()
                .RegisterTransient<IRandomVariableService, RandomVariableService>()
                .RegisterTransient<IBitmapLuminanceService, BitmapLuminanceService>()
                .RegisterTransient<IFileDialogService, FileDialogService>()
                .RegisterTransient<INonBlockDialogService, NonBlockDialogService>()
                .RegisterTransient<IColorMatrixService, ColorMatrixService>()
                .RegisterTransient<IAsyncOperationLocker, AsyncOperationLocker>()
                .RegisterTransient<IConvolutionProvider, ConvolutionProvider>()
                .RegisterTransient<IMorphologyProvider, MorphologyProvider>()
                .RegisterTransient<IBitmapLuminanceProvider, BitmapLuminanceProvider>()
                .RegisterTransient<IRgbProvider, RgbProvider>()
                .RegisterTransient<IScalingProvider, ScalingProvider>()
                .RegisterTransient<IRotationProvider, RotationProvider>()
                .RegisterTransient<ITransformationProvider, TransformationProvider>()
                .RegisterTransient<IChartSeriesBuilder, ChartSeriesBuilder>()
                .RegisterTransient<IQualityMeasureService, QualityMeasureService>()
                .RegisterTransient<IHistogramService, HistogramService>()
                .RegisterTransient<IBitmapLuminanceVisitableFactory, BitmapLuminanceVisitableFactory>()
                .RegisterTransient<IBitmapLuminanceVisitor, BitmapLuminanceVisitor>()
                .RegisterTransient<IConvolutionVisitor, ConvolutionVisitor>()
                .RegisterTransient<ICovolutionVisitableFactory, ConvolutionVisitableFactory>()
                .RegisterTransient<IHistogramVisitor, HistogramVisitor>()
                .RegisterTransient<IHistogramVisitableFactory, HistogramVisitableFactory>();
        }
    }
}
